# Generated by Django 3.2.9 on 2021-12-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user',
            new_name='user_profile',
        ),
    ]
